---
- name: Configure insecure ports for Db2 subsystems (v12 & v13)
  hosts: zos_host
  collections:
    - ibm.ibm_zos_core
  gather_facts: false
  environment: "{{ environment_vars }}"
  tasks:
  
    - name: Stop DBD1 subsystem.
      zos_operator:
        cmd: "-DBD1 STOP DB2"
        wait_time_s: 30
        verbose: true
      
    - name: Submit DSNTIJUL job for DBD1
      zos_job_submit:
        src: DB2.V13R1M0.NEW.SDSNSAMP(DSNTIJUL)
        location: DATA_SET
        wait_time_s: 15

    - name: START DBD1 subsystem.
      zos_operator:
        cmd: "-DBD1 START DB2"
        wait_time_s: 30
        verbose: true

    - name: Stop DBC1 subsystem.
      zos_operator:
        cmd: "-DBC1 STOP DB2"
        wait_time_s: 30
        verbose: true
      
    - name: Submit DSNTIJUL job for DBC1
      zos_job_submit:
        src: DB2.V12R1M0.NEW.SDSNSAMP(DSNTIJUL)
        location: DATA_SET
        wait_time_s: 15

    - name: START DBC1 subsystem.
      zos_operator:
        cmd: "-DBC1 START DB2"
        wait_time_s: 30
        verbose: true
