- name: Authorize library in APF.
  hosts: zos_host
  environment: "{{ environment_vars }}"
  gather_facts: false
  tasks:

    - name: "Before running tasks, display contents of SYS1.PARMLIB's member {{ prog_mem_list }}"
      ansible.builtin.command:
        cmd: "cat 'SYS1.PARMLIB({{ item }})'"
      changed_when: false
      loop: "{{ prog_mem_list }}"

    - name: Allocate PDSE (let ACS assign SMS classes)
      ibm.ibm_zos_core.zos_data_set:
        name: "{{ library }}"
        type: pdse
        record_format: fb
        record_length: 80
        block_size: 0
        space_primary: 20
        space_secondary: 10
        space_type: cyl
        state: present

    - name: Ensure dynamic APF format.
      ibm.ibm_zos_core.zos_apf:
        operation: set_dynamic

    - name: Get APF list to ensure idempotency.
      ibm.ibm_zos_core.zos_apf:
        operation: list
      register: apf_list

    - name: Ensure library is in APF list across IPLs.
      ibm.ibm_zos_core.zos_apf:
        library: "{{ library }}"
        sms: true
        persistent:
          data_set_name: "SYS1.PARMLIB({{ item }})"
      when: library not in apf_list.stdout
      loop: "{{ prog_mem_list }}"

    - name: Check APF list.
      ibm.ibm_zos_core.zos_apf:
        operation: list
      register: apf_list
      failed_when: library not in apf_list.stdout

    - name: Print APF list to terminal for visual verification.
      ansible.builtin.debug:
        var: apf_list.stdout

    - name: "After running tasks, display contents of SYS1.PARMLIB's member {{ prog_mem_list }}"
      ansible.builtin.command:
        cmd: "cat 'SYS1.PARMLIB({{ item }})'"
      changed_when: false
      loop: "{{ prog_mem_list }}"
