- name: Authorize library in APF.
  hosts: zos_host
  environment: "{{ environment_vars }}"
  gather_facts: false
  # Example list for batch_lib_list:
  # vars:
  #   batch_lib_list:
  #     - library: <lib_name>
  #       sms: true
  #     - library: <lib_name>
  #       volume: <vol_name>
  tasks:

    - name: Allocate PDSE (let ACS assign SMS classes)
      ibm.ibm_zos_core.zos_data_set:
        name: "{{ library }}"
        type: pdse
        record_format: fb
        record_length: 80
        block_size: 0
        space_primary: 20
        space_secondary: 10
        space_type: cyl
        state: present

    - name: Set dynamic libraries to the APF list.
      ibm.ibm_zos_core.zos_apf:
        library: "{{ library }}"
        sms: true
        operation: set_dynamic
        state: present

    - name: Ensure APF list is persistent across IPLs.
      ibm.ibm_zos_core.zos_apf:
        library: "{{ library }}"
        sms: true
        persistent:
          data_set_name: SYS1.PARMLIB(PROG3A)
        state: present

    - name: Get APF list.
      ibm.ibm_zos_core.zos_apf:
        operation: list
      register: apf_list
      failed_when: batch_lib_list.library not in apf_list.stdout

    - name: Print APF list to terminal for visual verification.
      ansible.builtin.debug:
        var: apf_list.stdout
