- name: Example playbook for z/OS
  hosts: zos_host
  environment: "{{ environment_vars }}"
  gather_facts: false
  tasks:

    - name: Execute a USS command.
      ansible.builtin.command:
        cmd: hostname
      changed_when: false

    - name: Ensure PDS is allocated.
      ibm.ibm_zos_core.zos_data_set:
        name: IBMUSER.ANSIBLE.EXAMPLE
        type: PDS
        state: present

    - name: Submit JCL.
      ibm.ibm_zos_core.zos_job_submit:
        src: "{{ playbook_dir }}/zos_concepts/jobs/submit_query_retrieve/files/{{ job_name | upper }}.jcl"
        location: LOCAL
        wait_time_s: 60
        encoding:
          from: ISO8859-1
          to: IBM-037
      register: job_submit
