---
- name: Execute IMS Commands
  hosts: zos_host
  gather_facts: false
  environment: '{{ environment_vars }}'
  vars:
    ims_command: "{{ ims_command_survey }}"
    ims_plex: "{{ ims_plex_survey | default('PLEX1') }}"
    ims_ssid: "{{ ims_ssid | default('IVP1') }}"
  tasks:
    - name: Execute IMS command.
      ibm.ibm_zos_ims.ims_command:
        command: "{{ ims_command }}"
        plex: "{{ ims_plex }}"
        route: "{{ ims_ssid }}"
      register: command_output
      ignore_erorrs: true

    - name: Print IMS command output.
      ansible.builtin.debug:
        msg: "{{ command_output.ims_output }}"

# Other example commands to try:
  # - display status
  # - display act reg
  # - query db name(*) show(all)
  #   - dis tran all
  #   - dis pgm all

# Operator Commands:
#   - s ims15om1
#   - s ims15sci