- name: Lightspeed z/OS tasks.
  hosts: zos_host
  gather_facts: false
  environment: "{{ environment_vars }}"
  tasks:
    # - name: Ping z/OS.
    # - name: Run z/OS TSO command to LISTUSER for user IBMUSER.
    # - name: Create a z/OS dataset member called IBMUSER.ANSIB.DATASET(DEMO1) with default parameters.
    # - name: Copy z/OS PDS member IBM.ANSIB.DATASET(DEMO1) to (DEMO2)
    # - name: Submit JCL from ~/templates/test.jcl.j2 template.
