- name: Reset password on z/OS RACF.
  hosts: zos_host
  environment: "{{ environment_vars }}"
  gather_facts: false
  tasks:
    - name: Execute TSO command to reset password on RACF.
      ibm.ibm_zos_core.zos_tso_command:
        commands: "ALU {{ userid | upper }} RESUME PASSWORD({{ lookup('ansible.builtin.password', '/dev/null', chars=['ascii_uppercase', 'digits'], length=8) }})"
        max_rc: 0
      register: temp_passwd

    - name: List user to verify passdate age.
      ibm.ibm_zos_core.zos_tso_command:
        commands: "LU {{ userid | upper }}"
        max_rc: 0
      register: listuser
      failed_when: "'PASSDATE=00.000' not in listuser.output"

    # - name: Send email to user with their temporary password.
    #   community.general.mail:
    #     host: <redacted>
    #     port: 25
    #     from: "<redacted>"
    #     to: "{{ tower_user_name }}"
    #     subject: "{{ inventory_hostname }}"
    #     body: "{{ temp_passwd }}"
