- name: Reset password on z/OS RACF.
  hosts: zos_host
  environment: "{{ environment_vars }}"
  gather_facts: false
  vars:
    userid_fmt: "{{ userid | upper }}"
  tasks:
    - name: Generate temporary password.
      ansible.builtin.set_fact:
        temp_passwd: "{{ lookup('ansible.builtin.password', '/dev/null', chars=['ascii_uppercase', 'digits'], length=8) }}"
      no_log: true

    - name: Check that the user ID format is valid
      ansible.builtin.assert:
        that:
          - userid_fmt is match('[A-Z0-9][0-9]{0,6}$')
          - userid_fmt | length < 8
        fail_msg: The provided USERID is not approved to be reset.

    - name: Execute TSO command to reset password on RACF using temporary password.
      ibm.ibm_zos_core.zos_tso_command:
        commands: "ALU {{ userid_fmt | upper }} RESUME PASSWORD({{ temp_passwd }})"
        max_rc: 0
      register: passwd_reset
      no_log: true

    - name: List user to verify passdate age.
      ibm.ibm_zos_core.zos_tso_command:
        commands: "LU {{ userid_fmt | upper }}"
        max_rc: 0
      register: listuser

    # - name: Send email to user with their temporary password.
    #   community.general.mail:
    #     host: <redacted>
    #     port: 25
    #     from: "<redacted>"
    #     to: "{{ tower_user_name }}"
    #     subject: "Password reset details on {{ inventory_hostname }}."
    #     body: >
    #       HOST: {{ inventory_hostname }}
    #       USERID: {{ userid_fmt }}
    #       TEMP PASSWD: {{ temp_passwd }}
    #   no_log: true

    - name: Success.
      ansible.builtin.debug:
        msg: "The USERID has been reset successfully and user has been informed via email."
