---
- name: IMS TMDB Provisioning
  hosts: zos_host
  gather_facts: false
  vars_files:
    - vars_wazi/ims-dbdc.yml
  environment: '{{ environment_vars }}'

  tasks:
    - name: Provision IMS for Wazi.
      vars:
        uss_file_path: '{{ tmdb_tmp_dir.path }}'
      block:

        - name: Run set_up_run_environment role.
          ansible.builtin.include_role:
            name: set_up_run_environment

        - name: Validate user inputs
          ansible.builtin.include_role:
            name: check_inputs
          vars:
            fail_task: true

        - name: Check if IMS already up
          ansible.builtin.include_role:
            name: check_duplicate_ims

        - name: Check if IMSPlex already up
          ansible.builtin.include_role:
            name: check_duplicate_imsplex

        - name: Check if ports are available
          ansible.builtin.include_role:
            name: check_port

        - name: Run provision_ims role.
          ansible.builtin.include_role:
            name: provision_ims

        - name: Run monitor_ims role.
          ansible.builtin.include_role:
            name: monitor_ims

      always:
        - name: Delete the temporary provision files directory
          ansible.builtin.file:
            path: "{{ tmdb_tmp_dir.path }}"
            state: absent
