---
- name: Delete a z/OS data set.
  hosts: zos_host
  gather_facts: false
  environment: "{{ environment_vars }}"
  tasks:

    - name: Delete a z/OS data set.
      ibm.ibm_zos_core.zos_data_set:
        name: "{{ ds_name | default('IBMUSER.ANSIBLE.DATASET') }}"
        state: absent
      register: ds_delete

    - name: Response for deleting the dataset.
      ansible.builtin.debug:
        msg: "{{ ds_delete }}"
